services:
  facial_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  facial_web_backend:
    image: facial_web_backend
    volumes:
      - .:/app
    entrypoint: ./entrypoint.sh
    build: . 
    ports:
      - "8000:8000"
    depends_on:
      - facial_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@facial_database:5432/app_db

volumes:
  pgdata: