services:
  facial_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  facial_web_backend:
    image: facial_web_backend
    environment:
      - DATABASE_URL=postgresql+psycopg://app_user:app_password@facial_database:5432/app_db
      - UPLOADS_DIR=/app/uploads
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - facial_database
    volumes:
      - uploads:/app/uploads

volumes:
  pgdata:
  uploads: