"""Status column to lower case

Revision ID: 0b399c6f7e00
Revises: 9f207b713ea2
Create Date: 2024-12-27 00:20:36.186477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b399c6f7e00'
down_revision: Union[str, None] = '9f207b713ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### 
    op.execute("CREATE TYPE userstatus_new AS ENUM ('active', 'inactive')")
    op.add_column(
        'users',
        sa.Column('status_new', sa.Enum('active', 'inactive', name='userstatus_new'), nullable=True, server_default='active')
    
    )
    op.execute("UPDATE users SET status_new = 'active' WHERE status = 'Ativado'")
    op.execute("UPDATE users SET status_new = 'inactive' WHERE status = 'Desativado'")
    
    op.drop_column('users', 'status')
    op.execute("DROP TYPE userstatus")

    op.execute("ALTER TYPE userstatus_new RENAME TO userstatus")
    op.alter_column('users', 'status_new', new_column_name='status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userstatus_new AS ENUM ('Ativado', 'Desativado')")
    op.add_column(
        'users',
        sa.Column('status_new', sa.Enum('Ativado', 'Desativado', name='userstatus_new'), nullable=True, server_default='Ativado')
    
    )
    op.execute("UPDATE users SET status_new = 'Ativado' WHERE status = 'active'")
    op.execute("UPDATE users SET status_new = 'Desativado' WHERE status = 'inactive'")
    
    op.drop_column('users', 'status')
    op.execute("DROP TYPE userstatus")
    
    op.execute("ALTER TYPE userstatus_new RENAME TO userstatus")
    op.alter_column('users', 'status_new', new_column_name='status')
    # ### end Alembic commands ###
