"""Add last_accessed_by_user_id and last_access_time fields on environment table

Revision ID: 0ea691b901b9
Revises: e482f7e88589
Create Date: 2025-01-19 01:19:54.396864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea691b901b9'
down_revision: Union[str, None] = 'e482f7e88589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('last_accessed_by_user_id', sa.Integer(), nullable=True))
    op.add_column('environments', sa.Column('last_access_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'environments', 'users', ['last_accessed_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_column('environments', 'last_access_time')
    op.drop_column('environments', 'last_accessed_by_user_id')
    # ### end Alembic commands ###
