"""Add name to log on User and Environment schemas

Revision ID: 2043e80846bc
Revises: 7b7e8ec0047a
Create Date: 2025-01-19 14:29:23.667172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2043e80846bc'
down_revision: Union[str, None] = '7b7e8ec0047a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('last_accessed_by_user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_accessed_environment_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'environments', ['last_accessed_environment_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_accessed_environment_name')
    op.drop_column('environments', 'last_accessed_by_user_name')
    # ### end Alembic commands ###
