"""Incluindo mais campos na tabela do admin

Revision ID: 3540ef4107d8
Revises: b24699632a38
Create Date: 2024-12-09 15:26:45.939069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3540ef4107d8'
down_revision: Union[str, None] = 'b24699632a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('admins', sa.Column('cpf', sa.String(), nullable=False))
    op.add_column('admins', sa.Column('name', sa.String(), nullable=False))
    op.add_column('admins', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'admins', ['phone_number'])
    op.create_unique_constraint(None, 'admins', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'phone_number')
    op.drop_column('admins', 'name')
    op.drop_column('admins', 'cpf')
    op.drop_column('admins', 'date_of_birth')
    # ### end Alembic commands ###
