"""Add log field for user schema

Revision ID: 7b7e8ec0047a
Revises: 0ea691b901b9
Create Date: 2025-01-19 13:02:42.896578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7e8ec0047a'
down_revision: Union[str, None] = '0ea691b901b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_accessed_environment_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_access_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'environments', ['last_accessed_environment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_access_time')
    op.drop_column('users', 'last_accessed_environment_id')
    # ### end Alembic commands ###
