"""Add GIN index to new users.name_unaccent column using gin_trgm_ops

Revision ID: 80ed89d55f94
Revises: ab8f048a08a9
Create Date: 2024-12-25 18:22:00.924716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ed89d55f94'
down_revision: Union[str, None] = 'ab8f048a08a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column('name_unaccent', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE users
        SET name_unaccent = unaccent(name)
        """
    )
    op.alter_column(
        'users',
        'name_unaccent',
        nullable=False
    )
    op.create_index(
        'idx_users_name_gin_trgm',
        'users', ['name_unaccent'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'name_unaccent': 'gin_trgm_ops'}
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'idx_users_name_gin_trgm',
        table_name='users',
        postgresql_using='gin',
        postgresql_ops={'name_unaccent': 'gin_trgm_ops'}
    )
    op.drop_column('users', 'name_unaccent')
    # ### end Alembic commands ###
