"""Adding users_environments association table

Revision ID: adab90ee48f9
Revises: f8200cbd83f6
Create Date: 2024-12-13 16:15:25.579534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adab90ee48f9'
down_revision: Union[str, None] = 'f8200cbd83f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'environments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('creator_admin_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'users_environments',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('enviroment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['enviroment_id'], ['environments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'enviroment_id')
    )
    op.drop_table('enviroments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enviroments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('creator_admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], name='enviroments_creator_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='enviroments_pkey'),
    sa.UniqueConstraint('name', name='enviroments_name_key')
    )
    op.drop_table('users_environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
